create table customers (customer_id integer generated by default as identity,email_address   varchar(255) not null,full_name       varchar(255) not null);

create table stores (
  store_id          integer generated by default as identity ,
  store_name        varchar(255) not null,
  web_address       varchar(100),
  physical_address  varchar(512),
  latitude          double precision,
  longitude         double precision,
  logo              bytea,
  logo_mime_type    varchar(512),
  logo_filename     varchar(512),
  logo_charset      varchar(512),
  logo_last_updated date)
;
  
create table products (
  product_id         integer generated by default as identity ,
  product_name       varchar(255) not null,
  unit_price         decimal(10,2),
  product_details    JSONB)
;

---
create table orders (
  order_id        integer 
                  generated by default  as identity,
  order_datetime  timestamp not null,
  customer_id     integer not null,
  order_status    varchar(10) not null,
  store_id        integer not null)
;


create table shipments (
  shipment_id          integer 
                       generated by default  as identity,
  store_id             integer not null,
  customer_id          integer not null,
  delivery_address     varchar(512) not null,
  shipment_status      varchar(100) not null)
;

create table order_items (
  order_id        integer not null,
  line_item_id    integer not null,
  product_id      integer not null,
  unit_price      decimal(10,2) not null,
  quantity        integer not null,
  shipment_id     integer)
;


create table inventory (
  inventory_id          integer
                        generated by default as identity,
  store_id              integer not null,
  product_id            integer not null,
  product_inventory     integer not null)
;


----------------

create index customers_name_i on customers ( full_name );
create index orders_customer_id_i on orders ( customer_id );
create index orders_store_id_i on orders ( store_id );
create index shipments_store_id_i on shipments ( store_id );
create index shipments_customer_id_i on shipments ( customer_id );
create index order_items_shipment_id_i on order_items ( shipment_id );
create index inventory_product_id_i on inventory ( product_id );